language: java

services:
  - docker

install: skip
script: skip

jobs:
  include:
    - stage: test
      name: "Test orders service"
      script: ./gradlew :orders:check
    - name: "Test payments service"
      script: ./gradlew :payments:check
    - name: "Test stock service"
      script: ./gradlew :stock:check
    - name: "Test users service"
      script: ./gradlew :users:check
    - stage: build
      name: "Build orders service"
      script: ./ci/build.sh orders
    - name: "Build payments service"
      script: ./ci/build.sh payments
    - name: "Build stock service"
      script: ./ci/build.sh stock
    - name: "Build users service"
      script: ./ci/build.sh users
    - stage: end-to-end
      name: "Run end-to-end tests"
      script: ./ci/test.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
