language: java

services:
  - docker

install: skip
script: skip

jobs:
  include:
    - stage: test
      name: "Test orders service"
      script: ./gradlew :service:orders:check
    - name: "Test payments service"
      script: ./gradlew :service:payments:check
    - name: "Test stock service"
      script: ./gradlew :service:stock:check
    - name: "Test users service"
      script: ./gradlew :service:users:check
    - stage: build
      name: "Build orders service"
      script: ./ci/build.sh service:orders service/orders orders
    - name: "Build payments service"
      script: ./ci/build.sh service:payments service/payments payments
    - name: "Build stock service"
      script: ./ci/build.sh service:stock service/stock stock
    - name: "Build users service"
      script: ./ci/build.sh service:users service/users users
    - stage: end-to-end
      name: "Run end-to-end tests"
      script: ./ci/test.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
