version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:5:1"
  rest:
    image: wdmk/rest:${IMAGE_VERSION:-latest}
    build: service/rest
    links:
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  orders:
    image: wdmk/orders:${IMAGE_VERSION:-latest}
    build: service/orders
    links:
      - kafka
    ports:
      - "10001:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  payments:
    image: wdmk/payments:${IMAGE_VERSION:-latest}
    build: service/payments
    links:
      - kafka
    ports:
      - "10002:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  stock:
    image: wdmk/stock:${IMAGE_VERSION:-latest}
    build: service/stock
    links:
      - kafka
    ports:
      - "10003:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  users:
    image: wdmk/users:${IMAGE_VERSION:-latest}
    build: service/users
    links:
      - kafka
    ports:
      - "10004:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
