version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "orders:5:1"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - orders
      - payments
      - stock
      - users
    ports:
      - "8080:80"
  orders:
    image: wdmk/orders:${IMAGE_VERSION:-latest}
    build: orders
    links:
      - kafka
    ports:
      - "10001:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  payments:
    image: wdmk/payments:${IMAGE_VERSION:-latest}
    build: payments
    links:
      - kafka
    ports:
      - "10002:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  stock:
    image: wdmk/stock:${IMAGE_VERSION:-latest}
    build: stock
    links:
      - kafka
    ports:
      - "10003:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  users:
    image: wdmk/users:${IMAGE_VERSION:-latest}
    build: users
    links:
      - kafka
    ports:
      - "10004:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
