---
apiVersion: v1
kind: Pod
metadata:
  name: wdm-kafka-kafka
  labels:
    app: wdm-kafka
    service: kafka
spec:
  containers:
    - name: kafka
      image: wurstmeister/kafka
      ports:
        - containerPort: 9092
      env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://wdm-kafka-kafka:9092
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://0.0.0.0:9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: wdm-kafka-zookeeper:2181
      livenessProbe:
        tcpSocket:
          port: 9092
        initialDelaySeconds: 60
        periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: wdm-kafka-kafka
  labels:
    app: wdm-kafka
    service: kafka
spec:
  type: ClusterIP
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: wdm-kafka
    service: kafka
