---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wdm-kafka-payments
  labels:
    app: wdm-kafka
    service: payments
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wdm-kafka
      service: payments
  serviceName: wdm-kafka-payments
  template:
    metadata:
      labels:
        app: wdm-kafka
        service: payments
    spec:
      containers:
        - name: payments
          image: wdmk/payments:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: wdm-kafka-kafka:9092
            - name: NUM_PARTITIONS
              value: "3"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
