---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdm-kafka-rest
  labels:
    app: wdm-kafka
    service: rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wdm-kafka
      service: rest
  template:
    metadata:
      labels:
        app: wdm-kafka
        service: rest
    spec:
      containers:
        - name: rest
          image: wdmk/rest:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            limits:
              memory: "2.5Gi"
            requests:
              memory: "2Gi"
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: wdm-kafka-kafka:9092
            - name: NUM_PARTITIONS
              value: "3"
---
apiVersion: v1
kind: Service
metadata:
  name: wdm-kafka-rest
  labels:
    app: wdm-kafka
    service: rest
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: wdm-kafka
    service: rest